#pragma once

#include "lvgl.h"

extern const lv_img_dsc_t flightsabove_icon_airliner;
extern const lv_img_dsc_t flightsabove_icon_heavy_2e;
extern const lv_img_dsc_t flightsabove_icon_jet_swept;
extern const lv_img_dsc_t flightsabove_icon_cessna;
extern const lv_img_dsc_t flightsabove_icon_glider;
extern const lv_img_dsc_t flightsabove_icon_helicopter;
extern const lv_img_dsc_t flightsabove_icon_unknown;
extern const lv_img_dsc_t flightsabove_icon_type_b738;
extern const lv_img_dsc_t flightsabove_icon_type_b38m;
extern const lv_img_dsc_t flightsabove_icon_type_b739;
extern const lv_img_dsc_t flightsabove_icon_type_a21n;
extern const lv_img_dsc_t flightsabove_icon_type_a321;
extern const lv_img_dsc_t flightsabove_icon_type_e75l;
extern const lv_img_dsc_t flightsabove_icon_type_c172;
extern const lv_img_dsc_t flightsabove_icon_type_b737;
extern const lv_img_dsc_t flightsabove_icon_type_b39m;
extern const lv_img_dsc_t flightsabove_icon_type_b763;
extern const lv_img_dsc_t flightsabove_icon_type_a359;
extern const lv_img_dsc_t flightsabove_icon_type_b789;
extern const lv_img_dsc_t flightsabove_icon_type_b77l;
extern const lv_img_dsc_t flightsabove_icon_type_b77w;
extern const lv_img_dsc_t flightsabove_icon_type_c68a;
